from Model.Operatore import Operatore
from Model.Operazione import Operazione
from Model.Stazione_Sismica import Stazione_Sismica
from Model.Esterno import Esterno
from Model.Log_In import Log_In
from Model.Recapito import Recapito
from Model.Percorso import Percorso
from Model.Veicolo import Veicolo
from Model.Responsabile import Responsabile
from Model.Foto import Foto
from Model.Nota import Nota
from Model.Componente import Componente
from Model.Componenti.Batteria import Batteria
from Model.Componenti.MemoriaMassa import Memoria_Massa
from Model.Componenti.PannelloSolare import Pannello_Solare
from Model.Componenti.Cavo import Cavo
from Model.Componenti.RegolatoreCarica import Regolatore_Carica
from Model.Componenti.Gps import Gps
from Model.Componenti.Sensore import Sensore
from Model.Componenti.Acquisitore import Acquisitore
from Model.Nrl import NRL
from Model.Localizzazione import Localizzazione
from Model.Canale import Canale
