"""empty message

Revision ID: 27bb66a216b7
Revises: 0949e2b0186c
Create Date: 2020-04-03 10:46:31.663548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bb66a216b7'
down_revision = '0949e2b0186c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'doors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
